version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      POSTGRES_USER: strader_user
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: strader_db
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  timescaledb-data:
