services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: strader_user
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: strader_db
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strader_user -d strader_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-backup:
    image: timescale/timescaledb:latest-pg16
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backup_database.sh:/usr/local/bin/backup_database.sh
      - ./backups:/backups
    environment:
      - BACKUP_DIR=/backups
      - POSTGRES_HOST=db
      - POSTGRES_DB=strader_db
      - POSTGRES_USER=strader_user
      - POSTGRES_PASSWORD=my-secret-pw
    command: ["sh", "/usr/local/bin/backup_database.sh"]

  backend:
    build:
      context: ./stock-data-backend
      target: final
    restart: always
    depends_on:
      db-backup:
        condition: service_completed_successfully
    environment:
      - DB_HOST=db
      - DB_NAME=strader_db
      - DB_USER=strader_user
      - DB_PASSWORD=my-secret-pw
      - DB_PORT=5432
      - NEWS_API_KEY=285e22d197ff4ea6a6ae6112009d6c71
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend-test:
    build:
      context: ./stock-data-backend
      target: test
    depends_on:
      db-backup:
        condition: service_completed_successfully
    environment:
      - DB_HOST=db
      - DB_NAME=strader_test_db # Use a separate database for testing
      - DB_USER=strader_user
      - DB_PASSWORD=my-secret-pw
      - DB_PORT=5432
    command: ["python", "-m", "pytest"]

volumes:
  timescaledb-data:
